# Generated by Django 2.2.12 on 2020-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='File name: ',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Book author: '),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Book name: '),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_house',
            field=models.CharField(max_length=200, verbose_name='Publish institution: '),
        ),
    ]
