# Generated by Django 2.2.12 on 2020-08-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200817_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='File name: ',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.CharField(default='', max_length=200, verbose_name='File name: '),
        ),
    ]
