# Generated by Django 2.2.12 on 2020-08-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20200817_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='', max_length=10, verbose_name='状态：'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, verbose_name='作者：'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.CharField(default='', max_length=300, verbose_name='软件包：'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=200, verbose_name='名字：'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_house',
            field=models.CharField(max_length=200, verbose_name='来源机构：'),
        ),
    ]
