# Generated by Django 2.2.12 on 2020-08-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200817_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwarePackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='软件名')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('pub_house', models.CharField(max_length=200, verbose_name='来源机构')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('file', models.CharField(default='', max_length=300, verbose_name='申请软件包')),
                ('status', models.CharField(default='', max_length=10, verbose_name='状态')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
