# Generated by Django 2.2.12 on 2020-08-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20200817_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SoftwarePackages',
            new_name='SoftwarePackage',
        ),
    ]
